# Generated by Django 5.0 on 2023-12-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.CharField(max_length=500, verbose_name='описание')),
                ('picture', models.ImageField(upload_to='', verbose_name='изображение (превью)')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.CharField(max_length=500, verbose_name='описание')),
                ('picture', models.ImageField(upload_to='', verbose_name='изображение (превью)')),
                ('video', models.CharField(max_length=500, verbose_name='ссылка на видео')),
            ],
        ),
    ]
