# Generated by Django 5.0 on 2023-12-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='picture',
            field=models.ImageField(null=True, upload_to='', verbose_name='изображение (превью)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='picture',
            field=models.ImageField(null=True, upload_to='', verbose_name='изображение (превью)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.CharField(max_length=500, null=True, verbose_name='ссылка на видео'),
        ),
    ]
