# Generated by Django 5.0 on 2023-12-21 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_kurs_description_alter_kurs_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='kurs',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lessons.kurs'),
        ),
    ]
