# Generated by Django 5.0 on 2023-12-21 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_kurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='kurs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.kurs'),
        ),
    ]
