# Generated by Django 5.0 on 2023-12-22 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_lesson_kurs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='дата платежа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='оплачено')),
                ('type', models.CharField(choices=[('1', 'наличные'), ('2', 'перевод на банковский счет')], default='2', max_length=1, verbose_name='способ оплаты')),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.kurs', verbose_name='курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
