# Generated by Django 5.0 on 2024-01-02 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_alter_lesson_video_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='kurs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.kurs'),
        ),
    ]
