# Generated by Django 5.0 on 2024-01-03 13:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_alter_subscription_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kurs',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='kurs',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='kurs',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='kurs',
            new_name='course',
        ),
    ]
