# Generated by Django 5.0 on 2024-01-05 18:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_rename_kurs_course_rename_kurs_lesson_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntens',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Запрошено')),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='оплачено')),
            ],
        ),
    ]
