# Generated by Django 5.0 on 2024-01-05 22:23
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_paymentintens'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintens',
            name='payment_id',
            field=models.CharField(max_length=150, null=True, verbose_name='УИ платежа в банке'),
        ),
        migrations.AlterField(
            model_name='paymentintens',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
