# Generated by Django 5.0 on 2024-01-05 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_paymentintens_payment_id_alter_paymentintens_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentintens',
            old_name='payment_id',
            new_name='payments_id',
        ),
    ]
